//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.DataAccess
{
    using Dominio.Model.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlquilerVehiculosEntities : DbContext
    {
        public AlquilerVehiculosEntities()
            : base("name=AlquilerVehiculosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cabecera_alquiler> cabecera_alquiler { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalle_alquiler> detalle_alquiler { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
