//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea_Etiqueta
    {
        public int idTarea_Etiqueta { get; set; }
        public int idTarea { get; set; }
        public int idEtiqueta { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
